language: node_js
sudo: false
node_js:
  - "10.1"
install:
  - npm install
script:
  - npm run lint
  - npm test
after_success:
  - nyc report --reporter=text-lcov --check-coverage npm test | npx coveralls
