language: node_js
sudo: false
node_js:
  - "10.1"
before_install:
  - npm install -g npm@6 && npm install -g npx && node -v && npm -v
install:
  - npm install
script:
  - npm run lint
  - npm run test:coverage && nyc report --reporter=text-lcov | npx coveralls

